{
 "title": "Conso Elec",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "my_interval", "label": "Interval", "query": "30m,1h,6h,12h,1d,7d,14d,30d" },
   {
    "name": "tarif_abo_hphc",
    "label": "Abonnement annuel Heures Pleines / Heures Creuses",
    "query": "163.44"
   },
   { "name": "tarif_hp", "label": "Tarif HP", "query": "0.1708" },
   { "name": "tarif_hc", "label": "Tarif HC", "query": "0.1286" }
  ]
 },
 "panels": [
  {
   "title": "Index Heure Creuse",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "HCHC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Conso 1d",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "HCHC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "/  1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tarif HC Période",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HCHC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "/  1000 * $tarif_hc" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tarif en cours",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "PTEC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tarif HP Période",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "HCHP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "/  1000 * $tarif_hp" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Index Heure Pleine",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "HCHP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Evolution Index",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "pleines",
     "measurement": "HCHP",
     "query": "SELECT mean(\"value\")::integer AS value FROM \"HCHC\" WHERE $timeFilter GROUP BY time(1s) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "creuses",
     "measurement": "HCHC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Puissance apparante / Intensité",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "yaxes": [
    { "format": "kvoltamp", "label": "Puissance" }
   ],
   "targets": [
    {
     "alias": "puissance_apparente",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PAPP",
     "query": "SELECT mean(\"value\")::integer AS value FROM \"HCHC\" WHERE $timeFilter GROUP BY time(1s) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "intensite",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "IINST",
     "query": "SELECT mean(\"value\")::integer AS value FROM \"HCHC\" WHERE $timeFilter GROUP BY time(1s) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consommation électrique en euros ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "alias": "Heures Creuses",
     "groupBy": [
      { "params": [ "$my_interval" ], "type": "time" }
     ],
     "measurement": "HCHC",
     "query": "SELECT (last(\"value\") - first(\"value\")),  FROM \"HCHC\" WHERE $timeFilter GROUP BY time($my_interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ " / 1000 * $tarif_hc" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Heures Pleines",
     "groupBy": [
      { "params": [ "$my_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HCHP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "/ 1000  * $tarif_hp" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heures creuses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "hc",
     "measurement": "HCHC",
     "query": "SELECT mean(\"value\")::integer AS value FROM \"HCHC\" WHERE $timeFilter GROUP BY time(1s) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heures pleines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "pl",
     "measurement": "HCHP",
     "query": "SELECT mean(\"value\")::integer AS value FROM \"HCHC\" WHERE $timeFilter GROUP BY time(1s) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}